/* eslint-disable */
//
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "use-boolean": {
    name: "use-boolean",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-boolean.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("@/registry/hooks/use-boolean.tsx")),
    source: "",
  },
  "use-toggle": {
    name: "use-toggle",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-toggle.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("@/registry/hooks/use-toggle.tsx")),
    source: "",
  },
  "use-copy-to-clipboard": {
    name: "use-copy-to-clipboard",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-copy-to-clipboard.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("@/registry/hooks/use-copy-to-clipboard.tsx")
    ),
    source: "",
  },
}
